name: Delete endpoint

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Input a tag"
        type: string
        required: true

jobs:
  validate_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Tags
        run: |
          all_tags=$(git tag -l)
          echo "All Tags $all_tags"
        shell: bash

      - name: Get Tags
        run: |
          all_tags=$(git tag -l)
          if [[ "$all_tags" =~ (^|[[:space:]])$INPUT_TAG($|[[:space:]]) ]]; then
            echo "Tag exists in the repository."
            exit 0
          else
            echo "Tag does not exist in the repository."
            exit 1
          fi
        env:
          INPUT_TAG: ${{ github.event.inputs.tag }}

  build:
    runs-on: ubuntu-latest
    needs: [validate_tag]
    steps:
      - name: Print Selected Tag
        run: echo "Selected Tag ${{ inputs.tag }}"
