name: Delete endpoint

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Choose a tag"
        required: true
        options: ${{ steps.get_tags.outputs.tags }}

jobs:
  get_tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.extract_tags.outputs.tags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Tags
        id: extract_tags
        run: echo "::set-output name=tags::$(git tag -l)"

  build:
    runs-on: ubuntu-latest
    needs: [get_tags]
    steps:
        - name: Print Selected Tag
          run: echo "Selected Tag: ${{ needs.get_tags.outputs.tags }}"