name: Delete endpoint

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Input a tag"
        type: string
        required: true

jobs:
  validate_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: ${{ inputs.tag }}

      - run: echo "Tag exists!"
        if: steps.check-tag.outputs.exists == 'true'

  build:
    runs-on: ubuntu-latest
    needs: [validate_tag]
    steps:
      - name: Print Selected Tag
        run: echo "Selected Tag ${{ inputs.tag }}"
