name: Deploy endpoint

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  upload-model:
    uses: ./.github/workflows/upload-model.yml

  deploy:
    needs: upload-model
    runs-on: ubuntu-latest

    steps:
      - name: Get upload model output
        run: echo "Upload model result is ${{needs.upload-model.outputs.model_s3_path}}"

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
