name: Upload model

on:
  workflow_dispatch:
  workflow_call:

env:
  COMMIT_HASH: ${{ github.sha }}

jobs:
  upload_model:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.return_s3_path.outputs.MODEL_S3_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Return s3 path
        id: return_s3_path
        run: |
          echo "MODEL_S3_PATH='s3/folder/${{ env.COMMIT_HASH }}.model.tar'" >> $GITHUB_OUTPUT
