name: Upload model

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      model_s3_path:
        description: "The first output string"
        value: ${{ jobs.upload_model.outputs.model_s3_path }}

env:
  COMMIT_HASH: ${{ github.sha }}

jobs:
  upload_model:
    runs-on: ubuntu-latest
    outputs:
      model_s3_path: ${{ steps.return_s3_path.outputs.MODEL_S3_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Return s3 path
        id: return_s3_path
        run: |
          echo "MODEL_S3_PATH=s3/folder/${{ env.COMMIT_HASH }}.model.tar" >> $GITHUB_OUTPUT
