name: Upload model

on:
  workflow_dispatch:
  workflow_call:

env:
  COMMIT_HASH: ${{ github.sha }}

jobs:
  upload_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if tag exists
        run: |
          echo "${{ env.COMMIT_HASH }}"
