name: Upload model

on:
  workflow_dispatch:
  workflow_call:

env:
  COMMIT_HASH: ${{ github.sha }}

jobs:
  upload_model:
    runs-on: ubuntu-latest
    outputs:
      MODEL_ENV: ${{ steps.variables.outputs.MODEL_ENV}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        id: variables
        run: |
          # Add the commit hash to the model_env.json file
          jq --arg commit_hash "$COMMIT_HASH" '. + { "commit_hash": $commit_hash }' model_env.json > model_env_temp.json
          mv model_env_temp.json model_env.json

          echo "MODEL_ENV='$(jq -c . < model_env.json)'" >> $GITHUB_OUTPUT
          echo $MODEL_ENV
