name: Upload model

on:
  workflow_dispatch:
  workflow_call:

env:
  COMMIT_HASH: ${{ github.sha }}

jobs:
  upload_model:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.return_s3_path.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Return s3 path
        id: return_s3_path
        run: |
          echo "::set-output name=result::${{ env.COMMIT_HASH }}"
